version: '3'
#docker run --name mi-postgress -e POSTGRES_PASSWORD=mi-contrasena -p 5432:5432 -d postgres
services:
  PostgreSQL:
    image: postgres
    container_name: mi-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mi-contrasena
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: localhost #mi-postgres
    restart: always
    user: postgres #root
  api:
    build: .
    ports:
      - "8080:8080"
